version: '3.9'

services:
  rclone:
    container_name: rclone
    image: rclone/rclone
    volumes:
      - ./${DATA}:/${DATA}:shared
      - ./rclone:/config/rclone/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    entrypoint: rclone mount ${Network_Disk_Name}:/ /${DATA} --copy-links --no-gzip-encoding --no-check-certificate --allow-other --allow-non-empty --umask 000 --vfs-cache-max-size 8G --vfs-cache-max-age 3m --vfs-cache-mode writes
    devices:
      - "/dev/fuse:/dev/fuse"
    healthcheck:
      test: cat /${DATA}/config.json
      interval: 5s
      timeout: 30s
      retries: 50
      
  brec:
    container_name: brec
    image: bililive/recorder
    volumes:
      - ./${DATA}:/${DATA}:shared
    ports:
      - "${PORT}:${PORT}"
    entrypoint: dotnet /app/BililiveRecorder.Cli.dll run --bind "http://${HOST}:${PORT}" --http-basic-user "${username}" --http-basic-pass "${password}" "/${DATA}"
    depends_on:
      rclone:
        condition: service_healthy